<a href="https://colab.research.google.com/github/dnyandeobharambe/pytorchlearn/blob/main/autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

import torch
# reuires_grad = True tracks gradient required any operation on also tracks it
x = torch.randn(3,requires_grad=True)
print(x)
y = x + 2
print(y)
z = y*y*2
print(z)
t = z.median()
print(t)

#to calculate gradient of t with respect to x that is dt/dx
# this works as t is scalar 
# note it required requires_grad= True on tensor
#retain_graph=True used below as x.grad calculated again for dz/dx
t.backward(retain_graph=True)
print(x.grad)

#calculate dz/dx
# it errorout as internally it use vector jacolian method
# it is multiplication of matrix with vector it also called as chain rule
# so matrix should multiply be vector

#z.backward()
#print(x.grad)

#it modified as below for dz/dx
v = torch.tensor([0.1,1.0,0.0001], requires_grad=True)

z.backward(v)
print(x.grad)


tensor([-0.6406, -0.2666,  0.1082], requires_grad=True)
tensor([1.3594, 1.7334, 2.1082], grad_fn=<AddBackward0>)
tensor([3.6960, 6.0095, 8.8893], grad_fn=<MulBackward0>)
tensor(6.0095, grad_fn=<MedianBackward0>)
tensor([0.0000, 6.9337, 0.0000])
tensor([5.4376e-01, 1.3867e+01, 8.4329e-04])


In [1]:
# in pyrtch during training grad accumlated and gives wrong gradient
# so it should reset before next run

import torch
weights = torch.ones(4,requires_grad=True)
for epoch in range(3):
  model_output = (weights*3).sum()
  model_output.backward()
  print(weights.grad)
# we can this result is wrong as it should be always 3
# so we need to reset it by adding weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([6., 6., 6., 6.])
tensor([9., 9., 9., 9.])


In [2]:
import torch
weights = torch.ones(4,requires_grad=True)
for epoch in range(3):
  model_output = (weights*3).sum()
  model_output.backward()
  print(weights.grad)
  weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
